### ISSUE TITLE
failed to load the plugin

### ISSUE THREAD

**Issue by uuuuzerr99** [vzsky/blindfold-obsidian#1]
Hi, I like the idea of your Obsidian plugin.
Tried to install it manually, as I did sucessfully with other Obsidian plugins. 
But with this plugin there might be a problem/bug... I always get the message "failed to load the plugin" if I try to activate it in the settings.

Thx in advance for your contribution by creating such a useful plugin  and please let me know when there is a solution to this behaviour.
Marc

**Comment by vzsky** [comment]
Hi, Thank you for checking out the plugin. 

As I could install it manually and I am completely new to making plugin, could you walk me through the process of manually installing the plugin? If I know the process I might be able to recreate the bug and solve the problem. 

Also, If you would like to, please feel free to leave a suggestion or request of feature.

Thanks.

**Comment by uuuuzerr99** [comment]
Hi, the manual installation process is quite simple.
You take the whole folder with all the components of the plugin and copy it to:
C:\...\Obsidian\Testvault\.obsidian\plugins\blindfold-obsidian-1.0.0
Then you make sure, that the external plugins are allowed (-> limited Mode is deactivated). 
And you activate the plugin after a restart...

I think that's it. 

Hope this helped you, otherwise there are tutorials somewhere on youtube or other platforms... 
Thx for your reply.
Marc

**Comment by vzsky** [comment]
I don't think that that method would install the plugin.

Before listing as an official community plugin, you could install it manually by either

1. Download the files `manifest.json`, `main.js`, `styles.css` from the release tab and put it in the folder named obsidian-blindfold under the plugin directory

2. Download the entire folder and place it under plugin directory like you did, then run `yarn build` in that folder.

However, I have not tested using Windows.
So if there is any error during any process, feel free to leave a comment.

**Comment by uuuuzerr99** [comment]
Hi, ok I have found the problem (under Windows 11)!

My install procedure was: 
1) downloading the Source Code blindfold-obsidian-1.0.0.zip file from https://github.com/vzsky/blindfold-obsidian/releases/tag/1.0.0 and unpack the folder.
2) copy it to the folder structure mentioned above

My findings:
+ the .zip folder contains a lot of additional files, as it contains the source code... nevertheless should work, as it always did for me!
+ but comparing file extensions, I found out, that there seemed to happen a little mistake in the file name extension of the main.js file - it was mislabeled as a .ts file instead of .js

My repair work:
+ so I downloaded just the main.js file from https://github.com/vzsky/blindfold-obsidian/releases/tag/1.0.0 and copied it to the folder mentioned above. And instantly everything worked. 
+ for just doing it right I also downloaded the manifest and styles file copied it into the folder and deleted the rest of the source code files. But this should not be necessary, as it alwalys worked this way with other souce code files from the unpacked .zip folder.

So, probably you can review and update your .zip sourcecode file package with the correct main.js file ending.

Nevertheless, I like your idea of hiding Information with this Obsidian plugin, because I want to use it a lot... for several usecases.
I will experiment with it in the coming days. 

Thank you for creating this plugin. 
Marc

**Comment by vzsky** [comment]
Thank you for sharing, and I am happy that you found a way to install the plugin. 

However, `main.js` is definitely required for a plugin to work. However, `main.ts` file is not a typo.
`main.js` is intended to be generated and release in rounds. So that 

- by downloading from the release tab, you are guaranteed to received tested update, whereas the code on GitHub might be under development.

Therefore, I am not planning to include a `main.js` file in the zip.

**If I am not mistaken**, other plugins might require _this method_ for installation as well, as it would be the _standard?_ way, although details may vary as per the developer of those plugins.
