### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gwesley96** [vzsky/blindfold-obsidian#2]
Hi, 

I use your plugin as an integral part of my vault for my math notes. Will there be a new release soon? 

Thank you!

**Comment by vzsky** [comment]
Hi!
Happy you like it. For now, there is no releases queuing, however, if you have anything in mind, feel free to suggest them.

Edit: I noticed I have not released the latest changes of this repository. I will do it hopefully tonight, otherwise in a few days.

**Comment by gwesley96** [comment]
Thank you so much, I appreciate it!

**Comment by vzsky** [comment]
I have pushed a new release. Enjoy!
