### ISSUE TITLE
Feature request: named buttons

### ISSUE THREAD

**Issue by o-petrov** [vzsky/blindfold-obsidian#3]
Is it possible to make folded buttons display specified text? e.g. 
```
 ```blindfold "See proof"
 long proof... or something... ```
```

will look like button titled "See proof" when folded.

**Comment by vzsky** [comment]
Actually a good idea and might not be hard to implement. But I am not available at the moment. If anyone would PR, it will be great.

**Comment by vzsky** [comment]
```
 ```blindfold See proof
something.                   ```
```

should work now in version 1.0.2
