### ISSUE TITLE
Feature request: in-text blindfolds

### ISSUE THREAD

**Issue by o-petrov** [vzsky/blindfold-obsidian#4]
Is it possible to add same thing inline instead of as separate block/paragraph? `blindfold here could be inline spoiler` or something like that.

**Comment by vzsky** [comment]
There are definitely other obsidian plugins doing this. But yes, including this in the same plugin is not a bad idea.

**Comment by vzsky** [comment]
I added this feature in version 1.0.2, you can now use inline spoiler by the following syntax.
|% inline spoiler %|
